### ISSUE TITLE
🔐 Database connections lack SSL/TLS encryption in production

### ISSUE THREAD

**Issue by kota-suzu** [kota-suzu/StockRx#52]
## Problem
Database configuration in `config/database.yml` does not enforce SSL/TLS connections for production environments.

## Impact
- **Severity**: High  
- Database traffic vulnerable to interception
- Sensitive inventory data transmitted unencrypted
- Compliance issues for production deployments

## Affected Files
- `config/database.yml` - Missing SSL configuration
- `docker-compose.yml` - Hardcoded database credentials

## Current State
```yaml
production:
  adapter: mysql2
  # Missing: sslmode, sslcert, etc.
```

## Solution
1. **Enable SSL for database connections**:
```yaml
production:
  adapter: mysql2
  sslmode: require
  sslcert: <%= ENV['DB_SSL_CERT'] %>
  sslkey: <%= ENV['DB_SSL_KEY'] %>
  sslrootcert: <%= ENV['DB_SSL_ROOT_CERT'] %>
```

2. **Move credentials to environment variables**:
```yaml
password: <%= ENV['DATABASE_PASSWORD'] %>
username: <%= ENV['DATABASE_USERNAME'] %>
```

3. **Update docker-compose.yml** to use Docker secrets instead of plain environment variables

## Acceptance Criteria
- [ ] SSL/TLS enabled for all database connections
- [ ] All database credentials moved to environment variables
- [ ] Docker secrets implemented for sensitive data
- [ ] Connection security verified in staging environment
- [ ] Documentation updated with security configuration

## Priority  
🔴 **Critical** - Required for production security compliance
