### ISSUE TITLE
🐳 Technical Debt: Docker configuration optimization for production

### ISSUE THREAD

**Issue by kota-suzu** [kota-suzu/StockRx#65]
## Problem
Current Docker configuration lacks production optimizations including multi-stage builds, resource limits, and improved security measures.

## Impact
- **Severity**: Low
- Inefficient deployments and resource usage
- Suboptimal container security
- Missing production deployment features

## Current Issues
1. **Missing multi-stage builds** for smaller production images
2. **No resource limits** defined for containers
3. **Backup strategy** needs improvement
4. **Security enhancements** needed for production

### 1. Multi-stage Dockerfile
```dockerfile
# Multi-stage build for smaller production images
FROM ruby:3.2-alpine AS builder
# Build dependencies and assets

FROM ruby:3.2-alpine AS production
# Production runtime only
COPY --from=builder /app /app
```

### 2. Resource Limits
```yaml
# docker-compose.production.yml
services:
  web:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
```

### 3. Security Enhancements
```yaml
services:
  web:
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
```

### 4. Production Compose File
Create separate `docker-compose.production.yml` with:
- Optimized resource allocation
- Security hardening
- Production-ready backup strategy
- Health checks and monitoring

## Acceptance Criteria
- [ ] Implement multi-stage Dockerfile for smaller images
- [ ] Add resource limits for all services
- [ ] Create production-specific docker-compose file
- [ ] Implement container security best practices
- [ ] Add proper health checks for all services
- [ ] Optimize backup container configuration
- [ ] Test production Docker configuration
- [ ] Document deployment procedures

## Priority
🟢 **Low** - Nice to have for production deployment efficiency
